name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare to Build Docker containers
      run: pwd && touch config/mongo.env && touch config/mongo-express.env && touch config/DB_ADMIN_CONFIG.env
    - name: Build the Docker images
      run: docker-compose build
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push docker images
      run: docker-compose push
