name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare to Build Docker containers
      run: pwd && ls && touch src/config/mongo.env && touch src/config/mongo-express.env && touch src/config/DB_ADMIN_CONFIG.env
    - name: Build the Docker images
      run: docker-compose build
    - name: Login to dockerhub and Push docker images
      run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }} && docker logout && docker login && docker-compose push
